import { useState, useEffect } from 'react'
import { Blog, Notification, Footer } from './components/blogs' 
import blogService from './services/blogs'
import './index.css'

const App = () => {
  const [blogs, setBlogs] = useState([])
  const [newBlog, setNewBlog] = useState('')
  const [newAuthor, setNewAuthor] = useState('')
  const [newUrl, setNewUrl] = useState('')
  const [showAll, setShowAll] = useState(true)
  const [errorMessage, setErrorMessage] = useState(null) // Changed to null

  useEffect(() => {
    blogService
      .getAll()
      .then(initialBlogs => {
        console.log('Received blogs from server:', initialBlogs)
       if (Array.isArray(initialBlogs)) {
        setBlogs(initialBlogs)
      }else {
        console.error('Expected an array of blogs but got:', initialBlogs)
      }
      })
  
  }, [])

  const addBlog = (event) => {
    event.preventDefault()
    const blogObject = {
      title: newBlog,
      author: newAuthor, 
      url: newUrl, 
      likes: 0 
      // The ID is generated by MongoDB automatically, don't put it here
    }

    blogService
      .create(blogObject)
      .then(returnedBlog => {
        setBlogs(blogs.concat(returnedBlog))
        setNewBlog('')
        setNewAuthor('')
        setNewUrl('')
      })
        .catch(error => { 
          setErrorMessage('Failed to add blog: ' + error.message)
          setTimeout(() => {
            setErrorMessage(null)
          }, 5000)
  }) }
//Adding a handler for blog title input changes
  const handleBlogChange = (event) => {
    setNewBlog(event.target.value)
  }
// Adding a handler for author input changes
  const handleAuthorChange = (event) => {
    setNewAuthor(event.target.value)
  }
  // Adding a handler for URL input changes
  const handleUrlChange = (event) => {
    setNewUrl(event.target.value)
  }


  const toggleLikesOf = (id) => {
    const blog = blogs.find(b => b.id === id)
    const changedBlog = { ...blog, likes: (blog.likes || 0) + 1 }

    blogService
      .update(id, changedBlog)
      .then(returnedBlog => {
        setBlogs(blogs.map(b => b.id !== id ? b : returnedBlog))
      })
      .catch(error => {
        setErrorMessage(
          `the blog '${blog.title}' was already removed from server`
        )
        setTimeout(() => {
          setErrorMessage(null)
        }, 5000)
        setBlogs(blogs.filter(b => b.id !== id))
      })
  }

  const blogsToShow = showAll ? blogs : blogs.filter((blog) => blog.likes > 0)

  return (
    <div>
      <h1>Favorite Blogs</h1>
      <Notification message={errorMessage} />
      <div>
        <button onClick={() => setShowAll(!showAll)}>
          show {showAll ? 'liked' : 'all' }
        </button>
      </div>      
      <ul>
        {blogs.map(blog => (
          <Blog
            key={blog.id} 
            blog={blog} 
            toggleImportance={() =>toggleLikesOf(blog.id)}
          />
        ))}
      </ul>
      <form onSubmit={addBlog}>
        Name: <input value={newBlog} type= "text" placeholder='Name' onChange={handleBlogChange} /><br />
        Author: <input value= {newAuthor} type="text" placeholder="Author" onChange={handleAuthorChange} /><br />
        URL: <input value = {newUrl} type="text" placeholder="URL" onChange={handleUrlChange} />
        <button type="submit">save</button>
      </form>
      <Footer />
    </div>
  )
}

export default App
